# Generated by Django 4.0.6 on 2022-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_profile_delete_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Большой', 'Большой'), ('Средний', 'Средний'), ('Маленький', 'Маленький')], max_length=20, null=True),
        ),
    ]
