# Generated by Django 4.0.6 on 2022-07-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_profile_admin_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admin',
            new_name='administrator',
        ),
    ]
