# Generated by Django 4.0.6 on 2022-07-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_admin_profile_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
