# Generated by Django 4.0.6 on 2022-07-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Крупы', 'Крупы'), ('Мясо и яйца', 'Мясо и яйца'), ('Алкогольные напитки', 'Алкогольные напитки'), ('Сладости', 'Сладости'), ('Рыба и морепродукты', 'Рыба и морепродукты'), ('Красота и здоровье', 'Красота и здоровье'), ('Хозяйственные товары', 'Хозяйственные товары'), ('Дом и сад', 'Дом и сад'), ('Молочные продукты', 'Молочные продукты'), ('Напитки', 'Напитки'), ('Замороженное', 'Замороженное')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
