# Generated by Django 4.0.6 on 2022-07-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_initial'),
        ('dashboard', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.profile'),
        ),
    ]
